# Generated by Django 4.2.7 on 2026-05-02 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('employee', 'Employee')], default='employee', max_length=20)),
                ('is_approved', models.BooleanField(default=False)),
                ('id_card_image', models.ImageField(blank=True, null=True, upload_to='id_cards/')),
                ('generated_email', models.EmailField(blank=True, default='', max_length=254)),
                ('extracted_first_name', models.CharField(blank=True, default='', max_length=100)),
                ('extracted_last_name', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
